services:
  server:
    container_name: spy-server
    image: spy-server:latest
    env_file:
      - ../server/environments/.development.env
    build:
      context: ..
      dockerfile: server/docker/dockerfiles/Dockerfile
    ports:
      - "7777:7777"
    depends_on:
      spy-database:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  redis:
    image: redis:7.2-alpine
    container_name: spy-cache
    command: [ "redis-server", "--notify-keyspace-events", "Exg" ]
    env_file:
      - ../server/environments/.development.env
    ports:
      - "6379:6379"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G

  spy-database:
    image: postgres:15
    container_name: spy-database
    env_file:
      - ../server/environments/.development.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/spy-database/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
